// Shipping zones define rate + free-above threshold.
// Country list covers ISO 3166-1 minus sanctioned jurisdictions (RU, BY, IR, SY, KP, CU).
// Sorted alphabetically by display name for the checkout <select>.

export type ShippingZone = {
  label: string;
  rate: number;
  freeAbove: number;
};

export const SHIPPING_ZONES: Record<string, ShippingZone> = {
  DOMESTIC: { label: "Domestic (US)", rate: 12, freeAbove: 150 },
  NORTH_AM: { label: "North America", rate: 18, freeAbove: 200 },
  EU_CORE: { label: "Europe", rate: 28, freeAbove: 250 },
  EU_EXT: { label: "Extended Europe", rate: 32, freeAbove: 300 },
  ASIA_PAC: { label: "Asia / Pacific", rate: 32, freeAbove: 300 },
  LATAM: { label: "Latin America", rate: 28, freeAbove: 250 },
  MEA: { label: "Middle East / Africa", rate: 34, freeAbove: 300 },
  OTHER: { label: "Rest of world", rate: 38, freeAbove: 350 },
};

export type Country = {
  code: string;
  name: string;
  zone: keyof typeof SHIPPING_ZONES;
};

const RAW_COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", zone: "OTHER" },
  { code: "AL", name: "Albania", zone: "EU_EXT" },
  { code: "DZ", name: "Algeria", zone: "MEA" },
  { code: "AD", name: "Andorra", zone: "EU_CORE" },
  { code: "AO", name: "Angola", zone: "MEA" },
  { code: "AI", name: "Anguilla", zone: "LATAM" },
  { code: "AG", name: "Antigua and Barbuda", zone: "LATAM" },
  { code: "AR", name: "Argentina", zone: "LATAM" },
  { code: "AM", name: "Armenia", zone: "EU_EXT" },
  { code: "AW", name: "Aruba", zone: "LATAM" },
  { code: "AU", name: "Australia", zone: "ASIA_PAC" },
  { code: "AT", name: "Austria", zone: "EU_CORE" },
  { code: "AZ", name: "Azerbaijan", zone: "EU_EXT" },
  { code: "BS", name: "Bahamas", zone: "LATAM" },
  { code: "BH", name: "Bahrain", zone: "MEA" },
  { code: "BD", name: "Bangladesh", zone: "ASIA_PAC" },
  { code: "BB", name: "Barbados", zone: "LATAM" },
  { code: "BE", name: "Belgium", zone: "EU_CORE" },
  { code: "BZ", name: "Belize", zone: "LATAM" },
  { code: "BJ", name: "Benin", zone: "MEA" },
  { code: "BM", name: "Bermuda", zone: "NORTH_AM" },
  { code: "BT", name: "Bhutan", zone: "ASIA_PAC" },
  { code: "BO", name: "Bolivia", zone: "LATAM" },
  { code: "BA", name: "Bosnia and Herzegovina", zone: "EU_EXT" },
  { code: "BW", name: "Botswana", zone: "MEA" },
  { code: "BR", name: "Brazil", zone: "LATAM" },
  { code: "BN", name: "Brunei", zone: "ASIA_PAC" },
  { code: "BG", name: "Bulgaria", zone: "EU_EXT" },
  { code: "BF", name: "Burkina Faso", zone: "MEA" },
  { code: "BI", name: "Burundi", zone: "MEA" },
  { code: "KH", name: "Cambodia", zone: "ASIA_PAC" },
  { code: "CM", name: "Cameroon", zone: "MEA" },
  { code: "CA", name: "Canada", zone: "NORTH_AM" },
  { code: "CV", name: "Cape Verde", zone: "MEA" },
  { code: "KY", name: "Cayman Islands", zone: "LATAM" },
  { code: "CF", name: "Central African Republic", zone: "MEA" },
  { code: "TD", name: "Chad", zone: "MEA" },
  { code: "CL", name: "Chile", zone: "LATAM" },
  { code: "CN", name: "China", zone: "ASIA_PAC" },
  { code: "CO", name: "Colombia", zone: "LATAM" },
  { code: "KM", name: "Comoros", zone: "MEA" },
  { code: "CG", name: "Congo (Brazzaville)", zone: "MEA" },
  { code: "CD", name: "Congo (Kinshasa)", zone: "MEA" },
  { code: "CR", name: "Costa Rica", zone: "LATAM" },
  { code: "CI", name: "Côte d'Ivoire", zone: "MEA" },
  { code: "HR", name: "Croatia", zone: "EU_EXT" },
  { code: "CW", name: "Curaçao", zone: "LATAM" },
  { code: "CY", name: "Cyprus", zone: "EU_EXT" },
  { code: "CZ", name: "Czechia", zone: "EU_EXT" },
  { code: "DK", name: "Denmark", zone: "EU_CORE" },
  { code: "DJ", name: "Djibouti", zone: "MEA" },
  { code: "DM", name: "Dominica", zone: "LATAM" },
  { code: "DO", name: "Dominican Republic", zone: "LATAM" },
  { code: "EC", name: "Ecuador", zone: "LATAM" },
  { code: "EG", name: "Egypt", zone: "MEA" },
  { code: "SV", name: "El Salvador", zone: "LATAM" },
  { code: "GQ", name: "Equatorial Guinea", zone: "MEA" },
  { code: "ER", name: "Eritrea", zone: "MEA" },
  { code: "EE", name: "Estonia", zone: "EU_EXT" },
  { code: "SZ", name: "Eswatini", zone: "MEA" },
  { code: "ET", name: "Ethiopia", zone: "MEA" },
  { code: "FO", name: "Faroe Islands", zone: "EU_CORE" },
  { code: "FJ", name: "Fiji", zone: "ASIA_PAC" },
  { code: "FI", name: "Finland", zone: "EU_CORE" },
  { code: "FR", name: "France", zone: "EU_CORE" },
  { code: "PF", name: "French Polynesia", zone: "ASIA_PAC" },
  { code: "GA", name: "Gabon", zone: "MEA" },
  { code: "GM", name: "Gambia", zone: "MEA" },
  { code: "GE", name: "Georgia", zone: "EU_EXT" },
  { code: "DE", name: "Germany", zone: "EU_CORE" },
  { code: "GH", name: "Ghana", zone: "MEA" },
  { code: "GI", name: "Gibraltar", zone: "EU_CORE" },
  { code: "GR", name: "Greece", zone: "EU_EXT" },
  { code: "GL", name: "Greenland", zone: "EU_CORE" },
  { code: "GD", name: "Grenada", zone: "LATAM" },
  { code: "GP", name: "Guadeloupe", zone: "LATAM" },
  { code: "GU", name: "Guam", zone: "DOMESTIC" },
  { code: "GT", name: "Guatemala", zone: "LATAM" },
  { code: "GG", name: "Guernsey", zone: "EU_EXT" },
  { code: "GN", name: "Guinea", zone: "MEA" },
  { code: "GW", name: "Guinea-Bissau", zone: "MEA" },
  { code: "GY", name: "Guyana", zone: "LATAM" },
  { code: "HT", name: "Haiti", zone: "LATAM" },
  { code: "HN", name: "Honduras", zone: "LATAM" },
  { code: "HK", name: "Hong Kong", zone: "ASIA_PAC" },
  { code: "HU", name: "Hungary", zone: "EU_EXT" },
  { code: "IS", name: "Iceland", zone: "EU_CORE" },
  { code: "IN", name: "India", zone: "ASIA_PAC" },
  { code: "ID", name: "Indonesia", zone: "ASIA_PAC" },
  { code: "IQ", name: "Iraq", zone: "MEA" },
  { code: "IE", name: "Ireland", zone: "EU_CORE" },
  { code: "IM", name: "Isle of Man", zone: "EU_EXT" },
  { code: "IL", name: "Israel", zone: "MEA" },
  { code: "IT", name: "Italy", zone: "EU_CORE" },
  { code: "JM", name: "Jamaica", zone: "LATAM" },
  { code: "JP", name: "Japan", zone: "ASIA_PAC" },
  { code: "JE", name: "Jersey", zone: "EU_EXT" },
  { code: "JO", name: "Jordan", zone: "MEA" },
  { code: "KZ", name: "Kazakhstan", zone: "EU_EXT" },
  { code: "KE", name: "Kenya", zone: "MEA" },
  { code: "KI", name: "Kiribati", zone: "ASIA_PAC" },
  { code: "XK", name: "Kosovo", zone: "EU_EXT" },
  { code: "KW", name: "Kuwait", zone: "MEA" },
  { code: "KG", name: "Kyrgyzstan", zone: "ASIA_PAC" },
  { code: "LA", name: "Laos", zone: "ASIA_PAC" },
  { code: "LV", name: "Latvia", zone: "EU_EXT" },
  { code: "LB", name: "Lebanon", zone: "MEA" },
  { code: "LS", name: "Lesotho", zone: "MEA" },
  { code: "LR", name: "Liberia", zone: "MEA" },
  { code: "LY", name: "Libya", zone: "MEA" },
  { code: "LI", name: "Liechtenstein", zone: "EU_CORE" },
  { code: "LT", name: "Lithuania", zone: "EU_EXT" },
  { code: "LU", name: "Luxembourg", zone: "EU_CORE" },
  { code: "MO", name: "Macao", zone: "ASIA_PAC" },
  { code: "MG", name: "Madagascar", zone: "MEA" },
  { code: "MW", name: "Malawi", zone: "MEA" },
  { code: "MY", name: "Malaysia", zone: "ASIA_PAC" },
  { code: "MV", name: "Maldives", zone: "ASIA_PAC" },
  { code: "ML", name: "Mali", zone: "MEA" },
  { code: "MT", name: "Malta", zone: "EU_EXT" },
  { code: "MH", name: "Marshall Islands", zone: "ASIA_PAC" },
  { code: "MQ", name: "Martinique", zone: "LATAM" },
  { code: "MR", name: "Mauritania", zone: "MEA" },
  { code: "MU", name: "Mauritius", zone: "MEA" },
  { code: "MX", name: "Mexico", zone: "NORTH_AM" },
  { code: "FM", name: "Micronesia", zone: "ASIA_PAC" },
  { code: "MD", name: "Moldova", zone: "EU_EXT" },
  { code: "MC", name: "Monaco", zone: "EU_CORE" },
  { code: "MN", name: "Mongolia", zone: "ASIA_PAC" },
  { code: "ME", name: "Montenegro", zone: "EU_EXT" },
  { code: "MA", name: "Morocco", zone: "MEA" },
  { code: "MZ", name: "Mozambique", zone: "MEA" },
  { code: "MM", name: "Myanmar", zone: "ASIA_PAC" },
  { code: "NA", name: "Namibia", zone: "MEA" },
  { code: "NR", name: "Nauru", zone: "ASIA_PAC" },
  { code: "NP", name: "Nepal", zone: "ASIA_PAC" },
  { code: "NL", name: "Netherlands", zone: "EU_CORE" },
  { code: "NC", name: "New Caledonia", zone: "ASIA_PAC" },
  { code: "NZ", name: "New Zealand", zone: "ASIA_PAC" },
  { code: "NI", name: "Nicaragua", zone: "LATAM" },
  { code: "NE", name: "Niger", zone: "MEA" },
  { code: "NG", name: "Nigeria", zone: "MEA" },
  { code: "MK", name: "North Macedonia", zone: "EU_EXT" },
  { code: "NO", name: "Norway", zone: "EU_CORE" },
  { code: "OM", name: "Oman", zone: "MEA" },
  { code: "PK", name: "Pakistan", zone: "ASIA_PAC" },
  { code: "PW", name: "Palau", zone: "ASIA_PAC" },
  { code: "PS", name: "Palestine", zone: "MEA" },
  { code: "PA", name: "Panama", zone: "LATAM" },
  { code: "PG", name: "Papua New Guinea", zone: "ASIA_PAC" },
  { code: "PY", name: "Paraguay", zone: "LATAM" },
  { code: "PE", name: "Peru", zone: "LATAM" },
  { code: "PH", name: "Philippines", zone: "ASIA_PAC" },
  { code: "PL", name: "Poland", zone: "EU_EXT" },
  { code: "PT", name: "Portugal", zone: "EU_CORE" },
  { code: "PR", name: "Puerto Rico", zone: "DOMESTIC" },
  { code: "QA", name: "Qatar", zone: "MEA" },
  { code: "RE", name: "Réunion", zone: "MEA" },
  { code: "RO", name: "Romania", zone: "EU_EXT" },
  { code: "RW", name: "Rwanda", zone: "MEA" },
  { code: "KN", name: "Saint Kitts and Nevis", zone: "LATAM" },
  { code: "LC", name: "Saint Lucia", zone: "LATAM" },
  { code: "VC", name: "Saint Vincent and the Grenadines", zone: "LATAM" },
  { code: "WS", name: "Samoa", zone: "ASIA_PAC" },
  { code: "SM", name: "San Marino", zone: "EU_CORE" },
  { code: "ST", name: "São Tomé and Príncipe", zone: "MEA" },
  { code: "SA", name: "Saudi Arabia", zone: "MEA" },
  { code: "SN", name: "Senegal", zone: "MEA" },
  { code: "RS", name: "Serbia", zone: "EU_EXT" },
  { code: "SC", name: "Seychelles", zone: "MEA" },
  { code: "SL", name: "Sierra Leone", zone: "MEA" },
  { code: "SG", name: "Singapore", zone: "ASIA_PAC" },
  { code: "SX", name: "Sint Maarten", zone: "LATAM" },
  { code: "SK", name: "Slovakia", zone: "EU_EXT" },
  { code: "SI", name: "Slovenia", zone: "EU_EXT" },
  { code: "SB", name: "Solomon Islands", zone: "ASIA_PAC" },
  { code: "SO", name: "Somalia", zone: "MEA" },
  { code: "ZA", name: "South Africa", zone: "MEA" },
  { code: "KR", name: "South Korea", zone: "ASIA_PAC" },
  { code: "SS", name: "South Sudan", zone: "MEA" },
  { code: "ES", name: "Spain", zone: "EU_CORE" },
  { code: "LK", name: "Sri Lanka", zone: "ASIA_PAC" },
  { code: "SD", name: "Sudan", zone: "MEA" },
  { code: "SR", name: "Suriname", zone: "LATAM" },
  { code: "SE", name: "Sweden", zone: "EU_CORE" },
  { code: "CH", name: "Switzerland", zone: "EU_EXT" },
  { code: "TW", name: "Taiwan", zone: "ASIA_PAC" },
  { code: "TJ", name: "Tajikistan", zone: "ASIA_PAC" },
  { code: "TZ", name: "Tanzania", zone: "MEA" },
  { code: "TH", name: "Thailand", zone: "ASIA_PAC" },
  { code: "TL", name: "Timor-Leste", zone: "ASIA_PAC" },
  { code: "TG", name: "Togo", zone: "MEA" },
  { code: "TO", name: "Tonga", zone: "ASIA_PAC" },
  { code: "TT", name: "Trinidad and Tobago", zone: "LATAM" },
  { code: "TN", name: "Tunisia", zone: "MEA" },
  { code: "TR", name: "Türkiye", zone: "EU_EXT" },
  { code: "TM", name: "Turkmenistan", zone: "ASIA_PAC" },
  { code: "TC", name: "Turks and Caicos", zone: "LATAM" },
  { code: "TV", name: "Tuvalu", zone: "ASIA_PAC" },
  { code: "UG", name: "Uganda", zone: "MEA" },
  { code: "UA", name: "Ukraine", zone: "EU_EXT" },
  { code: "AE", name: "United Arab Emirates", zone: "MEA" },
  { code: "GB", name: "United Kingdom", zone: "EU_CORE" },
  { code: "US", name: "United States", zone: "DOMESTIC" },
  { code: "UY", name: "Uruguay", zone: "LATAM" },
  { code: "UZ", name: "Uzbekistan", zone: "ASIA_PAC" },
  { code: "VU", name: "Vanuatu", zone: "ASIA_PAC" },
  { code: "VE", name: "Venezuela", zone: "LATAM" },
  { code: "VN", name: "Vietnam", zone: "ASIA_PAC" },
  { code: "VG", name: "Virgin Islands (British)", zone: "LATAM" },
  { code: "VI", name: "Virgin Islands (U.S.)", zone: "DOMESTIC" },
  { code: "YE", name: "Yemen", zone: "MEA" },
  { code: "ZM", name: "Zambia", zone: "MEA" },
  { code: "ZW", name: "Zimbabwe", zone: "MEA" },
];

const sorted = [...RAW_COUNTRIES].sort((a, b) =>
  a.name.localeCompare(b.name, "en", { sensitivity: "base" }),
);

export const COUNTRIES: Country[] = [
  ...sorted,
  { code: "OTHER", name: "Other / not listed", zone: "OTHER" },
];

export function countryByCode(code: string): Country {
  return COUNTRIES.find((c) => c.code === code) ?? COUNTRIES[COUNTRIES.length - 1];
}

export function zoneForCountry(code: string): ShippingZone {
  const c = countryByCode(code);
  return SHIPPING_ZONES[c.zone];
}
