// AUTO-GENERATED by scripts/generate-catalog.mjs — DO NOT EDIT BY HAND.
// Source of truth: /content/*.json

import type { Product } from "./products";

export const BRAND_DATA = {
  "name": "Titan Peptide Lab",
  "domain": "titanpeptidelab.com",
  "tagline": "Nasal-first peptide research catalog.",
  "description": "A nasal-first peptide catalog built around low-friction spray formats, HPLC-verified purity, batch-matched COAs, and cold-chain shipping."
} as const;

export const WALLETS_DATA = {
  "btc": "bc1qkshtp26f3qjkcgfdr2275wed2e8wkw25tr7vsd",
  "eth": "0x24c5Fe40f83ae20De82ae3637b66DE8B0e5Cd362",
  "usdcErc": "0x24c5Fe40f83ae20De82ae3637b66DE8B0e5Cd362",
  "sol": "DEHeTxWAhXhmPBMYr5orRXDMMF1vUZ8E2vjB4CHowLQM",
  "usdcSol": "DEHeTxWAhXhmPBMYr5orRXDMMF1vUZ8E2vjB4CHowLQM"
} as const;

export const DISCOUNT_CODES_DATA = {
  "FIRST10": {
    "percent": 10,
    "label": "10% off first order"
  },
  "BULK15": {
    "percent": 15,
    "label": "15% off 3+ items"
  },
  "TITAN20": {
    "percent": 20,
    "label": "20% off $250+"
  },
  "VIP25": {
    "percent": 25,
    "label": "25% VIP access"
  }
} as const;

export const PRODUCTS_DATA: Product[] = [
  {
    "id": "bpc157-spray",
    "slug": "bpc-157-nasal-spray",
    "name": "BPC-157 Nasal Spray",
    "category": "nasal-spray",
    "price": 64.99,
    "compareAtPrice": 84.99,
    "size": "15mL · 500mcg/spray",
    "tagline": "Recovery, gut support, systemic repair",
    "description": "Body Protection Compound 157 delivered via precision atomizer. Researchers report rapid tissue recovery and systemic anti-inflammatory action. HPLC-verified ≥99% purity.",
    "benefits": [
      "Tissue repair & recovery",
      "Gut lining support",
      "Non-invasive delivery",
      "Sublingual-to-nasal bioavailability"
    ],
    "image": "/products/bpc157-spray.png",
    "featured": true,
    "bestseller": true
  },
  {
    "id": "selank-spray",
    "slug": "selank-nasal-spray",
    "name": "Selank Nasal Spray",
    "category": "nasal-spray",
    "price": 59.99,
    "compareAtPrice": 74.99,
    "size": "15mL · 750mcg/spray",
    "tagline": "Calm focus without sedation",
    "description": "Russian-developed anxiolytic nootropic peptide. Modulates GABA and serotonin pathways for calm, alert cognition. Trusted by researchers for anxiety and attention studies.",
    "benefits": [
      "Reduces anxiety",
      "Enhances focus",
      "Non-sedating",
      "Mood stabilizing"
    ],
    "image": "/products/selank-spray.png",
    "featured": true,
    "bestseller": true
  },
  {
    "id": "oxytocin-spray",
    "slug": "oxytocin-nasal-spray",
    "name": "Oxytocin Nasal Spray",
    "category": "nasal-spray",
    "price": 74.99,
    "compareAtPrice": 94.99,
    "size": "15mL · 400mcg/spray",
    "tagline": "Connection, calm, and social regulation research",
    "description": "Intranasal oxytocin peptide for social bonding, stress response, and calm-state research. Built for labs studying trust, social cognition, and autonomic regulation in a familiar spray format.",
    "benefits": [
      "Social cognition research",
      "Stress regulation studies",
      "Intranasal peptide delivery",
      "Lot-matched COA included"
    ],
    "image": "/products/oxytocin-spray.png",
    "featured": true,
    "newArrival": true
  },
  {
    "id": "pt141-spray",
    "slug": "pt-141-nasal-spray",
    "name": "PT-141 Nasal Spray",
    "category": "nasal-spray",
    "price": 69.99,
    "compareAtPrice": 89.99,
    "size": "10mL · 1mg/spray",
    "tagline": "Libido & arousal research",
    "description": "Bremelanotide (PT-141) — melanocortin receptor agonist. Acts on central nervous system pathways. Fast-onset, non-hormonal research compound.",
    "benefits": [
      "Central nervous system action",
      "Non-hormonal",
      "Fast onset (~45 min)",
      "Unisex research use"
    ],
    "image": "/products/pt141-spray.png",
    "featured": true
  },
  {
    "id": "semax-spray",
    "slug": "semax-nasal-spray",
    "name": "Semax Nasal Spray",
    "category": "nasal-spray",
    "price": 59.99,
    "compareAtPrice": 74.99,
    "size": "15mL · 1mg/spray",
    "tagline": "Cognitive performance & neuroprotection",
    "description": "Heptapeptide nootropic. Upregulates BDNF, supports memory, focus, and neural recovery. Stacks cleanly with Selank for cognitive-emotional balance.",
    "benefits": [
      "Memory & learning",
      "BDNF upregulation",
      "Neural recovery",
      "Stress resilience"
    ],
    "image": "/products/semax-spray.png",
    "featured": true
  },
  {
    "id": "selank-semax-stack",
    "slug": "selank-semax-stack",
    "name": "Selank + Semax Stack",
    "category": "stack",
    "price": 105,
    "compareAtPrice": 120,
    "size": "2 × 15mL",
    "tagline": "The legendary cognitive-emotional pair",
    "description": "The classic dual-spray protocol. Selank for calm, Semax for sharp. Run them in tandem for balanced cognitive performance under load.",
    "benefits": [
      "Save $15 vs separate",
      "Balanced stack",
      "Most popular combo",
      "Researcher favorite"
    ],
    "image": "/products/selank-semax-stack.png",
    "bestseller": true
  },
  {
    "id": "dsip-spray",
    "slug": "dsip-nasal-spray",
    "name": "DSIP Nasal Spray",
    "category": "nasal-spray",
    "price": 62.99,
    "compareAtPrice": 79.99,
    "size": "15mL · 500mcg/spray",
    "tagline": "Sleep quality and recovery-state research",
    "description": "Delta Sleep-Inducing Peptide delivered through a precision nasal atomizer. Suited to sleep architecture, recovery, and downshift-state research where a non-invasive format matters.",
    "benefits": [
      "Sleep architecture studies",
      "Recovery-state support",
      "Low-friction spray format",
      "HPLC-verified purity"
    ],
    "image": "/products/dsip-spray.png",
    "newArrival": true
  },
  {
    "id": "retatrutide",
    "slug": "retatrutide",
    "name": "Retatrutide",
    "category": "injectable",
    "price": 199.99,
    "size": "10mg lyophilized",
    "tagline": "Next-gen metabolic research",
    "description": "Triple-agonist (GLP-1/GIP/glucagon). Emerging compound for metabolic research. Limited availability.",
    "benefits": [
      "Triple receptor agonist",
      "Metabolic research",
      "Limited stock",
      "99%+ HPLC purity"
    ],
    "image": "/products/retatrutide.png",
    "newArrival": true
  },
  {
    "id": "bpc157-vial",
    "slug": "bpc-157-vial",
    "name": "BPC-157 (Injectable Vial)",
    "category": "injectable",
    "price": 54.99,
    "size": "5mg lyophilized",
    "tagline": "Classic research format",
    "description": "Lyophilized BPC-157 in 5mg vial. For researchers who prefer subcutaneous protocols. Reconstitute with bacteriostatic water.",
    "benefits": [
      "Higher potency per dose",
      "Lab-standard format",
      "99%+ HPLC purity",
      "Ships with COA"
    ],
    "image": "/products/bpc157-vial.png"
  },
  {
    "id": "cjc-ipa",
    "slug": "cjc-1295-ipamorelin",
    "name": "CJC-1295 + Ipamorelin Blend",
    "category": "injectable",
    "price": 119.99,
    "size": "5mg / 5mg blend",
    "tagline": "GH axis research blend",
    "description": "Pre-blended CJC-1295 (no DAC) with Ipamorelin. Most-studied GH secretagogue combo. Saves reconstitution steps.",
    "benefits": [
      "Pre-blended convenience",
      "GH axis research",
      "Two-peptide synergy",
      "99%+ HPLC purity"
    ],
    "image": "/products/cjc-ipa.png"
  },
  {
    "id": "tb500-vial",
    "slug": "tb-500-vial",
    "name": "TB-500 (Injectable Vial)",
    "category": "injectable",
    "price": 89.99,
    "size": "5mg lyophilized",
    "tagline": "Systemic recovery research",
    "description": "Thymosin Beta-4 fragment. Used in tissue repair and recovery studies. Pairs well with BPC-157 protocols.",
    "benefits": [
      "Thymosin Beta-4 active fragment",
      "Tissue regeneration research",
      "99%+ HPLC purity",
      "Ships with COA"
    ],
    "image": "/products/tb500-vial.png"
  }
];

export const PROMOS_DATA: Array<{
  id: string;
  headline: string;
  body?: string;
  code?: string;
  expiresAt?: string;
  active: boolean;
}> = [];
