#!/usr/bin/env node
// Reads content/*.json and emits src/lib/products.data.ts (inlined, client-safe).
// Runs automatically before `next build` and `next dev` via the `prebuild` / `predev` hooks.
// To modify the catalog, edit files under /content — never edit src/lib/products.data.ts by hand.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const CONTENT = path.join(ROOT, "content");
const OUT = path.join(ROOT, "src", "lib", "products.data.ts");

function loadJson(rel) {
  return JSON.parse(fs.readFileSync(path.join(CONTENT, rel), "utf8"));
}

function loadProducts() {
  const dir = path.join(CONTENT, "products");
  if (!fs.existsSync(dir)) return [];
  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".json")).sort();
  const products = files.map((f) => loadJson(path.join("products", f)));
  return products.sort((a, b) => {
    // Explicit rank wins (lower = earlier). Products without a rank fall to the
    // back and keep the legacy featured/bestseller/newArrival + alpha ordering.
    const rank = (p) =>
      typeof p.rank === "number" ? p.rank : Number.MAX_SAFE_INTEGER;
    const r = rank(a) - rank(b);
    if (r !== 0) return r;
    const score = (p) =>
      (p.featured ? -4 : 0) + (p.bestseller ? -2 : 0) + (p.newArrival ? -1 : 0);
    const d = score(a) - score(b);
    return d !== 0 ? d : a.name.localeCompare(b.name);
  });
}

function loadPromos() {
  const dir = path.join(CONTENT, "promos");
  if (!fs.existsSync(dir)) return [];
  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".json")).sort();
  return files.map((f) => loadJson(path.join("promos", f)));
}

const brand = loadJson("brand.json");
const products = loadProducts();
const promos = loadPromos();

const banner =
  "// AUTO-GENERATED by scripts/generate-catalog.mjs — DO NOT EDIT BY HAND.\n" +
  "// Source of truth: /content/*.json\n\n";

const body = `${banner}import type { Product } from "./products";

export const BRAND_DATA = ${JSON.stringify(
  {
    name: brand.name,
    legalName: brand.legalName,
    domain: brand.domain,
    tagline: brand.tagline,
    description: brand.description,
  },
  null,
  2
)} as const;

export const WALLETS_DATA = ${JSON.stringify(brand.wallets, null, 2)} as const;

export const DISCOUNT_CODES_DATA = ${JSON.stringify(
  brand.discountCodes,
  null,
  2
)} as const;

export const PRODUCTS_DATA: Product[] = ${JSON.stringify(products, null, 2)};

export const PROMOS_DATA: Array<{
  id: string;
  headline: string;
  body?: string;
  code?: string;
  expiresAt?: string;
  active: boolean;
}> = ${JSON.stringify(promos, null, 2)};
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);
console.log(
  `[catalog] wrote ${products.length} products, ${promos.length} promos → ${path.relative(ROOT, OUT)}`
);
